obophenotype/uberon

util/sim2jsonld.pl
This is an attempt to fix #1255.
=> Add property type declaration for in_taxon

Makefile
=> Add Makefile target for asserted-only artifact.

Makefile
See https://github.com/obophenotype/insect-anatomy-ontology/issues/8
﻿
=> merge in insect edit module

src/ontology/imports/ro_import.owl
fix double def for "overlaps"
1) deleted all defs
2) refreshed RO
=> Fix RO_import.owl

src/ontology/uberon.Makefile
Mainly by killing CP:XXX classes coming in from existential
see also #1963
=> Removing dangling CL classes

src/ontology/uberon.Makefile
To make PR easier to read:
```
ANNOTATE_ONTOLOGY_VERSION = annotate -V $(ONTBASE)/releases/$(VERSION)/$@ --annotation owl:versionInfo $(VERSION)
```
Fixes #2059
=> Add versioninfo to all main releases

src/ontology/uberon.Makefile
=> Add ontology iri where is missing

docs/odk-workflows/RepositoryFileStructure.md, src/ontology/Makefile, src/ontology/uberon-odk.yaml, src/ontology/uberon.Makefile
=> Make the mappings file into a proper component

src/ontology/imports/cl_import.owl
BDS is now importing multiple labels cause CL is not updated in uberon - to fix this, I refreshed CL import into uberon.
Minimal review needed, literally just ran `sh run.sh make imports/cl_import.owl`
=> Refreshed CL import

src/ontology/uberon.Makefile, src/sparql/delete-definition-dot.ru
=> Delete definitions dot

src/ontology/uberon-edit.properties
=> Fix typo in UBERON:0001272

src/ontology/uberon-edit.properties
=> Add UBERON:8410073 medullary region of kidney

src/ontology/uberon-edit.properties
Addresses second part of #2126
=> Edit UBERON:0001284 renal column

src/ontology/uberon-edit.properties
=> Add comments to 'medullary region of kidney' and 'renal medulla'

src/ontology/uberon-idranges.owl
=> Request to add new editor to uberon-idranges.owl

src/ontology/uberon.Makefile
Adding another round of makefile annotations so we can move forward with cleaning up the pipeline
see also #284
=> Update uberon.Makefile (clean up makefile)

src/patterns/data/upperTeeth.tsv, src/patterns/dosdp-patterns/upper_tooth_pattern.yaml
@dosumis could you check these?
=> adding upper tooth tsv

uberon-idranges.owl
Adding ID range so I can curate terms associated with the pulmonary system as part of the LungMap project.
=> Add ID range for Joshua Fortriede

.github/workflows/subset_report.yml
--left and --right arguments required an update, --left should represent old version and --right should represent new version while using robot diff command.
=> --left and --right argument adjustment

src/ontology/make-bridge-ontologies-from-xrefs.pl, src/ontology/uberon.Makefile, src/sparql/life-cycle-xrefs.sparql
=> Fix sparql query to update bridge files

src/ontology/uberon.Makefile
=> Add taxon constraint check back

src/ontology/uberon.Makefile
=> Adding some additional checks to CI

.github/workflows/diff.yml
swap left and right in unreasoned diff
addresses https://github.com/obophenotype/uberon/pull/2521#issuecomment-1151343168
=> swap left and right in unreasoned diff

src/ontology/uberon-idranges.owl
As @paulacalipho will be contributing to Uberon going forward, she will need an ID range.
=> Adding Paula's ID range

docs/odk-workflows/ReleaseWorkflow.md, docs/uberon-release.md, mkdocs.yaml
Fixes https://github.com/obophenotype/uberon/issues/2544
@matentzn - I've created a secondary document for this, not sure if you want me to integrate with the ODK release workflow. Not sure if updating the ODK will erase all that too.
Happy to do either, lmk. Thanks!
=> Update Uberon release workflow

src/ontology/Makefile, src/ontology/uberon-odk.yaml, src/ontology/uberon.Makefile
=> Add missing subsets to odk config file

src/ontology/bridge/uberon-bridge-to-mba.owl, src/ontology/uberon.Makefile
ok, less scary a link now, we have decided to keep the bridge making in ABA_uberon, but have now moved the new bridges to master branch and kept our old stuff in a branch instead. I've also update my need changes to bridge file here
=> update mba/dmba make goal link

src/ontology/bridge/uberon-bridge-to-emapa.obo, src/ontology/bridge/uberon-bridge-to-ev.obo, src/ontology/bridge/uberon-bridge-to-ev.owl, src/ontology/bridge/uberon-bridge-to-fma.obo, src/ontology/bridge/uberon-bridge-to-hba.obo, src/ontology/bridge/uberon-bridge-to-hba.owl, src/ontology/bridge/uberon-bridge-to-ma.obo, src/ontology/bridge/uberon-bridge-to-ma.owl
Apply [changes](https://github.com/obophenotype/uberon/pull/2625) done in the mappings of EMAPA, FMA, HBA, MA and EV.
=> Update bridge files

src/ontology/uberon.Makefile, src/sparql/inject-life-stages-subset.ru
=> Fix `life-stages-composite.owl`

src/ontology/bridge/uberon-bridge-to-mba.obo, src/ontology/bridge/uberon-bridge-to-mba.owl
Probably should have merged branch in my bridge repo before release - but in my mind I needed to do a uberon release first (I don't - its just for a report). Anyway updating bridge here :)
=> updating MBA bridge

src/ontology/bridge/uberon-bridge-to-mba.obo, src/ontology/bridge/uberon-bridge-to-mba.owl
@gouttegd - this PR should fix the Rhinal Incisure miscuration
Sorry about that >.< 
Will let QC run through and all, in course all day, so please do just merge this in when you want :) 
Related to https://github.com/obophenotype/uberon/pull/2695#issuecomment-1292500068
=> Fix MBA bridge miscuration

src/sparql/inject-life-stages-subset.ru
=> Extend SPARQL query to tag children of 'life cycle stage'

.github/workflows/diff.yml, README.md
=> add gogoeditdiff trigger

src/ontology/bridge/uberon-bridge-to-mba.obo, src/ontology/bridge/uberon-bridge-to-mba.owl
Verified MBA bridges and this should be a stable version for now.
=> Update MBA bridges

.github/workflows/diff.yml
This PR makes the diff action trigger with new comments
=> #gogoeditdiff trigger on new comment

src/ontology/bridge/uberon-bridge-to-mba.obo, src/ontology/bridge/uberon-bridge-to-mba.owl
Recently got QC running and spotted some mistakes, this PR just pulls the fixes in from the external repo
=> updated MBA bridge to fix some issues

src/ontology/uberon.Makefile
This PR changes the files to upload into the GH release. This will remove the imports.
=> Change files to upload in release

src/ontology/components/hra_subset.owl, src/ontology/components/mappings.owl, src/ontology/mappings/fbbt-mappings.sssom.tsv
=> Update imports, components and fbbt mappings

.github/workflows/auto-pr-ontobot.yml
=> adding temporal line

.github/workflows/auto-pr-ontobot.yml
=> revise def and logical axiom to cranial temporal crest

src/ontology/components/hra_subset.owl, src/ontology/components/mappings.owl, src/ontology/mappings/fbbt-mappings.sssom.tsv, src/patterns/definitions.owl
=> Refresh imports

.gitignore, src/ontology/Makefile, src/ontology/uberon-odk.yaml, src/ontology/uberon.Makefile
=> Add common-anatomy.owl artifact in release pipeline

src/ontology/uberon.Makefile
This is requested to run the release in a new computer that doesn't have the files yet.
=> Update links on Allen bridge

docs/uberon-editor-sop.md
Addresses:
#2363 Add guidance on abbreviations
#1997 Add guidance on dbxref formats
=> Addresses #2363 Add guidance on abbreviations & #1997 Add guidance on dbxref formats

docs/uberon-editor-sop.md
Update uberon-editor-sop.md to align with CL documentation regarding database cross-references
=> Update uberon-editor-sop.md to align with CL documentation regarding database cross-references

.github/CODEOWNERS
This will make @anitacaron, @matentzn and @gouttegd guardians of the main branch.
=> Add CODEOWNERS file to Uberon

src/sparql/illegal-annotation-property-violation.sparql
=> Change `foaf:depicted_by` to `foaf:depiction`

src/ontology/uberon-idranges.owl
Update inadvertently added contributor annotations and edit id-range
=> Update inadvertently added contributor annotations

.github/workflows/qc.yml
More details on https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target and https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
=> Add permission to post comment in forked PR from GH Action 

.github/workflows/diff.yml
=> Update github actions' version

.github/workflows/diff.yml
=> Temporary fix for docker setup timeout

.gitignore, docs/odk-workflows/ManageDocumentation.md, docs/odk-workflows/RepositoryFileStructure.md, src/ontology/Makefile, src/ontology/catalog-v001.xml, src/ontology/imports/orcidio_import.owl, src/ontology/uberon-odk.yaml, src/ontology/uberon.Makefile, src/sparql/orcids.sparql
Related to #3253 (ORCID names are being removed in diff)
I chose to have a separate import because the merged_import excludes individuals, and I wanted to enable this only for Orcidio. I created a custom rule for `imports/orcidio_import.owl` and imported it in `uberon-edit.obo`.
What do you think?
=> Fix ORCID individuals import

.gitignore, docs/history.md, docs/onboarding.md, docs/uberon-editor-sop.md, mkdocs.yaml
This PR updates Uberon docs to better (obook) design and fixes some build warnings while I was at it.
=> Update Uberon docs to better (obook) design

src/ontology/uberon-idranges.owl
=> Add new ID range to Tiago Lubiana

docs/bridges.md
Fix #3344 broken link to SSOM documentation
=> Fix #3344 broken link to SSOM documentation
