obophenotype/uberon

Makefile
The `materialized.owl` makefile target causes the NCBITaxon hierarchy axioms to be duplicated into the main Uberon file:
https://github.com/obophenotype/uberon/blob/f96afbf9df79f5abca742b68fcea2c2f282be75b/Makefile#L127-L130
I added `--exclude-duplicate-axioms` to prevent this. I'm not sure why ROBOT is even treating these as inferred; will need to look into that separately. This should fix https://github.com/geneontology/go-ontology/issues/12218.
=> Add ROBOT option to prevent NCBITaxon axioms being copied into Uberon.

uberon-idranges.owl
Add an idrange for anatomical terms coming from InterLex. This will
greatly simplify the process of automatically generating pull requests
so that terms will already have a valid uberon id and will not have to
be manually mapped back into InterLex, only confirmed/rejected for
inclusion.
=> uberon-idranges.owl range for InterLex requests

Makefile
Maybe this ensures that uberon is not accidentally released with equivalent classes..
=> checked no equivalent classes

src/sparql/taxon_constraint_never_in_taxon.ru
This fixes the issue of out of control memory usage in computing taxon subsets. This morning I had done a test in Protege and concluded the problem must lie within owltools, but this was a mistake. I was using the current Uberon release, but the problem only manifests with the increased number of never_in_taxon constraints in the edit file. There were previously 706, but the current number (2460) pushed ELK into some kind of bad behavior.
Instead of modeling disjoints as an intersection which is equivalent to Nothing, this change just uses a direct disjoint axiom, which it seems the ELK algorithm is better prepared to handle.
With this fix there is no need for the Ammonite script I proposed.
=> Use disjointWith instead of equivalence to Nothing, to avoid pathological reasoner behavior.

src/ontology/uberon.Makefile, src/sparql/delete_uberon_two_constraints.ru
added command `remove_uberon_two_constraints` that removes all never_in_taxon axioms for uberon:2x and implemented it
=> Removing uberon:2x never in taxon

src/ontology/uberon.Makefile
Make sure the cross-references for mappings (that have been moved to the components/mappings.owl file) are merged back early in the pipeline (in the first file derived from the -edit file), so that they end up in all generated artefacts.
This is the least disruptive option, as it allows to mimic closely the situation that existed before the mappings were moved to a separate component.
Without that, the mappings component is only merged at the end of the pipeline (when producing `uberon.owl`), when all other imports are merged.
=> Merge the mappings component early in the pipeline.

src/sparql/delete-definition-dot.ru
Update sparql query to also take some properties from `http://purl.obolibrary.org/obo/uberon/core`
Fixes #2129
=> Extend SPARQL to delete dot-definition

.gitignore, src/ontology/uberon-edit.properties
Closes #2230 'glomerular visceral epithelium' should be part of (or merged with) glomerular visceral layer.
Outcome: Manually 'merged' UBERON:0005751 ‘visceral layer of glomerular capsule’ with UBERON:0006852 ‘glomerular visceral epithelium’ by updating the label of the former to 'glomerular visceral epithelium’ and obsoleting the latter.
=> Closes #2230 'glomerular visceral epithelium' should be part of (or merged with) glomerular visceral layer

src/ontology/mappings/fbbt-mappings.sssom.tsv
Manual update of the FBbt mappings (this is not automated yet).
This update brings small corrections to the mappings – the kind of corrections that does not require changing the _terms_ that are mapped, on either side; only the mappings themselves are changed.
=> Update FBbt mappings

src/ontology/uberon.Makefile
We had a historical restriction that all files in the ontology should only use characters from the Latin-9 character set, even if is encoded in UTF-8. Such a restriction is no longer warranted.
Besides, if the intention behind this restriction was to avoid characters coded on more than 1 byte, then it failed at doing so, as the ontology already contains at least one character outside of the ASCII character set: “ö“ (in the definition of `atlanto-occipital joint`, UBERON:0000220), which is encoded on two bytes in UTF-8 (0xC3 0xB6). The fact that nobody seemingly ever complained about it reinforces the case for dropping the character set restriction.
We keep a check intended to verify that the ontology only contains *valid* UTF-8.
close #2292
=> Remove restriction to latin-9 character set.

.github/workflows/stale-issues.yml
Update the 'stale-issues' workflow to implement the decision mentioned in #2268.
Any pull request that has not seen any activity in one month will be tagged with `unreviewed` and a comment will be added with the following message:
"This PR has not seen any activity in the past month; if nobody comments or reviews it in the next week, the PR editor will be allowed to proceed with merging without explicit approval, should they wish to do so."
Pull requests may be explicitly marked with a tag `approval required` to prevent them from receiving this comment. This way, a PR editor (or anybody else) can express that they do wish the PR to be explicitly approved.
closes: #2268
=> Automatically ping PRs after one month of inactivity.

.github/workflows/stale-issues.yml
Explicitly exclude draft PRs from the automatic ping normally sent on PR that have not seen any activity for one month.
=> Do not ping unreviewed draft PRs.

.github/workflows/diff.yml
Fixes #2436 
Adding automated diff report for both unreasoned version and reasoned version. I have used current branch as left input and master branch as right input in the robot diff command. I have also used uberon-edit.obo for unreasoned version and uberon-simple.owl for reasoned version, as @shawntanzk suggested. 
Would be good if make steps and robot diff part is reviewed
=> 2436 add automated diff to uberon

src/ontology/make-bridge-ontologies-from-xrefs.pl, src/ontology/uberon.Makefile, src/sparql/life-cycle-xrefs.sparql
Update the bridge generation scripts so that, in species-specific bridges, terms that are cross-referenced with Uberon’s `life cycle` (UBERON:0000104 or its subclasses) are defined in the generated bridges as equivalent to the Uberon term `occuring in` (BFO:0000066) the specific taxon, rather than the Uberon term `being part of` (BF:0000050) the specific taxon.
This is dependent on having a list of all terms that are cross-referenced to the Uberon's `life cycle` hierarchy. Generating such a list is outside the scope of this patch.
Assuming the list of cross-referenced terms is available in a file named `lsxrefs.txt`, generate the bridges with
```sh
./run.sh make bridge/bridges BRIDGE_LSXREFS='-l ../lsxrefs.txt'
```
Here is an example of the effects of this patch on the …
=> bridges: Change relation to life cycle terms to BFO:0000066.

src/ontology/components/mappings.owl, src/ontology/mappings/fbbt-mappings.sssom.tsv, src/ontology/uberon.Makefile
Update the custom Makefile to automatically download the FBbt SSSOM file from the FBbt repository, and therefore automatically update the FBbt mappings.
Downloading the SSSOM file is made conditional on the `IMP` variable, so that the file is only refreshed when running with `IMP=true`. Updating the mappings is thus considered similar to refreshing the imports, which I believe is sensible.
=> Auto refresh fbbt mappings

mkdocs.yaml
also capitalized Editors Documentation to match Title Case of other references (even though my preference would be to make them all Sentence case)
=> fix typo Ubeorn

src/scripts/check-obo-for-standard-release.pl
=> Exclude dc-contibutor from OBO checks

src/ontology/Makefile, src/ontology/uberon-odk.yaml, src/sparql/label-synonym-polysemy-violation.sparql
Check for both Label and Synonym polysemy across Terms
This PR started as #2640 but then I tried to outsmart github and I managed to close it.
This PR detects synonym-synonym and label-synonym across different Terms (UBERON Ids).
Another implementation (but with the same logic and functionality) of this check was
used to detect and fix (merged) the followings issues:
* https://github.com/obophenotype/uberon/pull/2465
* https://github.com/obophenotype/uberon/pull/2470
* https://github.com/obophenotype/uberon/pull/2506
The backstory is in https://github.com/obophenotype/uberon/issues/2424
The existing check
https://robot.obolibrary.org/report_queries/duplicate_exact_synonym detects
only synonym-synonym violations. It was reported in
https://github.com/ontodev/robot/issues/607 but closed at …
=> Check for both Label and Synonym polysemy across Terms

src/ontology/bridge/uberon-bridge-to-mba.obo, src/ontology/bridge/uberon-bridge-to-mba.owl
This PR re-classifies several terms to fix inconsistencies regarding the “connectedness” of anatomical entities.
We distinguish between anatomical entities that are made of parts that are all connected (`anatomical structure`) and entities that are made of parts that are not all connected (`disconnected anatomical group`). But we do not enforce the distinction, and as a result we have terms referring to disconnected entities that are classified as (connected) `anatomical structure`.
This cause massive satisfiability problems when merging Uberon and FBbt, because FBbt does enforce a strict separation (with an explicit disjointness axiom) between `anatomical structure` and `disconnected anatomical group`.
This PR implements the fixes proposed in #2682:
* classify `non-connected functional …
=> Fix classification for disconnected entities

.github/workflows/diff.yml
This PR makes it so that gogoeditdiff will only be triggered with a comment saying #gogoeditdiff With new pushes, this will not change until someone comments #gogoeditdiff again.
This action will only work when it is merged into master, but as a proof of concept, see my fork: https://github.com/shawntanzk/uberon/pull/2
=> Make gogoeditdiff manual

src/scripts/sssom2xrefs.awk
FlyBase will now provide its mapping set with `semapv:crossSpecies*Match` relations. This commit updates the SSSOM-processing AWK script to accept `semapv:crossSpeciesExactMatch` predicates in addition to the former `skos:exactMatch`.
=> mappings: Allow the use of semapv:crossSpeciesExactMatch.

.github/workflows/stale-issues.yml
This commit updates the `stale-issues.yml` workflow to:
- upgrade to version 7 of the `stale` action (needed to cope with changes to GitHub Actions, notably the deprecation of Node.js v12);
- raise the `operations-per-run` limit from 30 (default) to 100; this should allow to process more issues in a single run while still keeping us from hitting the rate limits (set to 1,000 operations per hour for GitHub Actions).
=> Update the stale-issues workflow.

src/sparql/illegal-annotation-property-violation.sparql
This does not yet obsolete generic pharynx, but adds a scheduled-for-obsoletion.
This also adds a seperate insecr pharynx.
See #2728
=> generic pharnx changes, part 1. See #2728.

.github/workflows/auto-pr-ontobot.yml
Added
- `author` 
- `committer`
Which will be the person who creates the issue.
Removed:
- `token`
NOTE: `token` was generated from my account and hence all PRs generated by `ontobot` seemed to have been requested by me. This will put an end to it but the presence of `token` triggered QC GitHub Actions which will not happen henceforth (once this PR is merged). With this change the PR requester will be `github-actions` user.
=> Replace myself as PR creator by `GitHub-actions` when ontobot creates a PR

docs/current_release.md
Fixes https://github.com/obophenotype/uberon/issues/2849
Readme contains a redirect to documentation - not sure if we want to also just drop the purl link there? 
Happy for anyone to make changes directly on branch
Forgot if docs needs deployment or is on an automated github actions here
=> Fix download docs

src/sparql/illegal-annotation-property-violation.sparql
IAO:0000233 is [supposedly the annotation property to use](https://github.com/information-artifact-ontology/ontology-metadata/issues/102) for linking to a bug tracker issue, but it is still flagged as an “illegal” annotation. I assume this is an oversight.
=> Add IAO:0000233 to the list of allowed annotation properties.

src/ontology/uberon.Makefile
The recent overhaul of the preproprecessing step (#2968) introduced an invalid reference to RO:0002175. As a result, that annotation was now expanded along with the other annotations, instead of being explicitly left unexpanded as was the intention.
This PR fixes the invalid reference to restore the non-expansion of RO:00002175.
=> Fix invalid IRI to RO relation in preprocessing step.

src/ontology/uberon.Makefile
After cloning the `developmental-stage-ontologies` repo, we should use the products that have been committed there as they are, without trying to rebuild them.
This may mean we'll end up with less up-to-date things (if one of the taxon-specific stage ontology has been updated since the last time product files were committed to `developmental-stage-ontologies`), but it will prevent a failure of the `developmental-stage-ontologies` pipeline to cause a failure of the Uberon pipeline. If someone wants ultra-fresh developmental stage ontologies, then someone can take care of updating the `developmental-stage-ontologies` repo.
closes #3009
=> Do not (try to) rebuild the merged developmental stage ontologies.

.github/workflows/qc.yml
Addresses #3020 Edit nociceptor --> 'nociceptor nerve ending'
Addresses Uberon edits
=> Addresses #3020 Edit nociceptor --> 'nociceptor nerve ending'

.github/workflows/qc.yml
Fixes #3025 
This commit undoes the evil (my bad) which is switching to an unstable development snapshot for dev.
Sorry about the noise all, my bad.
@bvarner-ebi it is important that we do not use axiom annotations so freely; for synonyms, we consistently use oio:hasDbXref (even with URLs). If the URL is not evidence that the term can be used as a synonym, do not add it at all. 
@anitacaron the time has come to not listen to my technical advice too much anymore; switching to dev for QC was a wrong call by me, sorry about that! For the future, the only suggestion I do make is that, PRs should separate concerns: as @gouttegd suggests, we should at all times keep PRs to logical units that are easily reviewable, and have meaningful title like ("Using unstable development snapshot for QC (temp …
=> Undo using dev in QC and change "see also" in synonym annotation to xref

docs/uberon-editor-sop.md
Context: https://github.com/obophenotype/uberon/pull/3029
Update guidance on adding URL dbxrefs (uberon-editor-sop.md)
Once approved, update CL editor documentation.
=> Update guidance on adding URL dbxrefs (uberon-editor-sop.md)

src/ontology/Makefile, src/ontology/uberon-odk.yaml, src/sparql/id-format-violation.sparql
This PR fixes the bogus ID of 'insect pharynx' (8-digits ID instead of the standard 7-digits format) by obsoleting the original term and replacing it with a new term with a correctly minted ID.
It also adds a new QC check to help prevent any occurrence of similar bogus IDs in the future.
closes #3051
=> 3051 Fix 'insect pharynx' bogus ID and add ID format check

src/ontology/Makefile, src/ontology/uberon-odk.yaml
~The artefact `go-base.owl` is in reality a base plus artefact (base + the inferred axioms). This reduces the size of the `merged_import.owl` by half.~
Fixes #3057
=> Make base for GO import

src/ontology/imports/local-cteno.owl, src/ontology/imports/local-ehdaa2.owl
This PR fixes unsatisfiable classes recently found in composite-metazoan by:
1. removing a bogus axiom (likely coming from an old version of Uberon) in the local CTENO mirror;
2. removing a bogus axiom in the local EHDAA2 mirror;
3. removing the bogus mappings between Uberon’s `serous sac` and EMAPA:16060 and MA:0000005.
See individual commit messages for more details about each issue.
=> Fix composite unsats

README.md, mkdocs.yaml
The README file was not pointing to the SOP for curators and ontology editors.
OLS link also has been updated to OLS4
=> Update README.md file to direct to editors SOP file

src/ontology/imports/local-poro.owl
Our local copy of PORO (used when building composite-metazoan) contains bogus general class axioms that, through bridging axioms and because they involve high-level Uberon classes ('anatomical entity' and 'immaterial anatomical entity') ultimately affect a large number of classes in composite-metazoan.
We refresh our copy of PORO with the latest release in which the offending axioms have been fixed.
closes #1958
=> Refresh the local copy of PORO.

src/ontology/bridge/cl-bridge-to-zfa.owl, src/ontology/bridge/uberon-bridge-to-caro.owl, src/ontology/bridge/uberon-bridge-to-zfa.owl, src/ontology/mappings/cl-mappings.sssom.tsv, src/ontology/mappings/zfa-mappings.sssom.tsv, src/ontology/uberon.Makefile
This PR amends the recently introduced SSSOM-based bridge pipeline to use the latest version (0.6.1) of the SSSOM plugin for ROBOT. This allows to:
* make sure the mapping sets extracted from CL and ZFA have an ID and a license tag, as required by the SSSOM specification (the license is the same as the one used by the ontology those sets are derived from);
* (much more importantly) make sure the the CL-to-ZFA bridge is complete.
=> Small fixes to the new bridge pipeline

src/ontology/uberon.Makefile
The `uberon-nif-merged.owl` product has been impossible to build for (at least) several months (possibly much more than that) because the link we try to download the “NIF Gross Anatomy” from is dead.
Besides, the usefulness of this product, even if we could build it, is dubious since the latest available version of the “NIF Gross Anatomy” seems to only contain deprecated terms that have been replaced by Uberon terms.
Adding to that the fact that nobody raised a voice against the removal of the `uberon-nif-merged` product since such a removal was evoked (#3018), there is no obvious reason to keep in place the rules to create this product. So we remove them here.
closes #3018
=> Remove rules to create `uberon-nif-merged`.

src/ontology/uberon.Makefile
This PR updates the Uberon ROBOT plugin to [version 0.2.0](https://github.com/gouttegd/uberon-robot-plugin/releases/tag/uberon-robot-plugin-0.2.0). This versions includes the following features to the `uberon:merge-species` command:
* `-d`: drop declaration axioms for classes that have been merged;
* `-g`: try to translate general class axioms (GCAs) that refer to a class that has been merged;
* `-x`: translate more class expressions than what was possible with OWLTools’ `--merge-species-ontology` command.
We use those new features when creating the `composite-*` products.
closes #3132
=> Use features from latest Uberon plugin to generate composite-metazoan.

src/ontology/uberon.Makefile
This PR amends the composite pipeline so that the CARO bridges to Uberon and CL are no longer included in any composite-* product.
CARO has been superseded by Uberon itself, so merging those bridges should no longer be necessary.
The bridges themselves are still kept for whoever might need them.
closes #3139
=> Remove the CARO bridges from the composite pipeline.

src/ontology/uberon.Makefile
All `composite-*` products are built by, among other operations, stripping any disjointness axiom in the merged ontology. This is necessary as most `composite-*` products would be impossible to build otherwise (the `merge-species` step requires the ontology to be consistent, and most of the `collected-*` merges are not because of incompatibilities between Uberon and one or several of the taxon-specific ontologies).
This will not change anytime soon, but we should still at least _aim_ to achieve inter-ontology consistency in the (far) future. This has already been achieved at least for the `composite-drosophila` product (Uberon + CL + FBbt), so it _is_ possible.
This PR makes the removal of the disjointness axioms optional, so one can easily try to build a `composite-*` product with the …
=> Allow to optionally keep disjointness axioms when building composite products.

src/ontology/Makefile, src/ontology/uberon-odk.yaml, src/ontology/uberon.Makefile
This PR removes two release products that are completely redundant since they are identical to another release product:
* `basic.owl`: exactly identical to `uberon-basic.owl` except that is has a different ontology IRI;
* `metazoan-view.owl`: exactly identical to `basic.owl` (and therefore to `uberon-basic.owl`).
There’s no need to waste time building those products and waste space hosting them. If some some pipelines out there are dependent on those files, they should be updated to use `uberon-basic.owl` instead. And if these are old pipelines that for some reason can’t be updated, then we should just have one more redirection in Uberon’s PURL configuration.
[Download statistics](https://tooomm.github.io/github-release-stats/?username=obophenotype&repository=uberon) for the Uberon …
=> Remove basic.owl and metazoan-view.owl

.github/workflows/auto-pr-ontobot.yml
This commit updates the ontobot workflow (`auto-pr-ontobot`) to make it use a dedicated authentication token (`ONTOBOT_TOKEN`), rather than the default `GITHUB_TOKEN`.
This should ensures that PRs created by the bot can trigger other workflows, notably the CI workflow.
related to #3223
=> Use a dedicated token for the ontobot workflow.

src/ontology/uberon.Makefile
This PR is a minor cleanup of the custom Makefile.
It removes a step that converts the `$(COMPONENTSDIR)/external-disjoints.obo` file into an intermediate `$(TMPDIR)/external-disjoints.owl`.
The `external-disjoints.owl` file is only ever used with ROBOT, and ROBOT is perfectly able to consume directly an OBO file, there’s no need for an explicit conversion to OWL.
It also removes the step that copied both the OBO and OWL versions of that file to the top-level `bridge` directory, which does not make any sense:
* that directory only contains those two files;
* in that directory, these files are “unreachable” by whoever would want to download them from a PURL, because `http://purl.obolibrary.org/obo/uberon/bridge` redirects to the `src/ontology/bridge` directory, _not_ to the top-level …
=> Remove intermediate file `external-disjoints.owl`

src/ontology/Makefile, src/ontology/uberon-odk.yaml, src/ontology/uberon.Makefile
This PR replaces the custom code that was used to download and install ROBOT plugins by ODK-managed code.
The SSSOM plugin for ROBOT is bundled with the ODK, so we no longer need to manually download it.
As for the Uberon-specific plugin, we still need to download it but we can rely on the ODK to do that for us--all we need is to declare the need to use that plugin.
=> Use ODK-managed ROBOT plugins.

src/ontology/uberon.Makefile
This PR amends the code that refreshes the FBbt mapping set to:
* use the new canonical location of the set (`http://purl.obolibrary.org/obo/fbbt.sssom.tsv`, valid since today’s FBbt release, instead of the old `http://purl.obolibrary.org/obo/fbbt-mappings.sssom.tsv`);
* ensure the remote file is always downloaded (unless `IMP=false`) even if the target file already exists (otherwise the rule would always be ignored and the set would never be refreshed – this is a bug inadvertently introduced in #3249).
=> Fix downloading of FBbt mapping set

.github/workflows/post-release-diff.yml, src/ontology/diffs/Makefile
The same as we have in [CL](https://github.com/obophenotype/cell-ontology/blob/master/.github/workflows/post-release-diff.yaml)
=> GH Action to post release diff on release PR

.github/workflows/diff.yml
Remove alternative action to run docker on macos runner.  [GH increased memory on the ubuntu-latest label](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories), so we can update the diff action to use `ubuntu-latest`.
This also align more closely to the [same action available in CL](https://github.com/obophenotype/cell-ontology/blob/master/.github/workflows/diff.yml).
- Add branch status job before generating diff
- Create different jobs
It's also updated to generate the classified ontology on the base, which is now the case.
Technically fixes #3183
=> Update Robot diff GH Action on PRs

.github/workflows/diff.yml
This pull request adds a reference to the branch in the pull request. Missing part in the `edit_file` job in PR #3283. All other [jobs passed](https://github.com/obophenotype/uberon/actions/runs/9220853685).
=> Add branch reference in pull request - diff action

src/ontology/components/hra_depiction_3d_images.owl
Previously, the component had all versions of the 3D Reference Organs GLB files available. Now, only the latest versions, published in the 7th release, HRA v2.1, are available.
=> Update 3D Reference Organs from HRA 7th release

.github/workflows/qc.yml
ROBOT 1.9.6 (and its 0.6 ELK reasoner) can catch TC violations that ROBOT 1.9.5 does not detect.
If Uberon releases are manually performed using the latest ODK (1.5.2, which includes ROBOT 1.9.6), then it means that we could run at release time into TC violations that were undetected during the normal development cycle. (The fact that it didn’t happen for now is solely due to the fact that the TC check has been broken for the past 6 months, cf #3336.)
To avoid that, this commit updates the QC workflow to make it use the latest point release of the ODK.
=> Use ODK 1.5.2 for the CI test suite.

src/ontology/uberon.Makefile
RO is currently mirrored in Uberon using a custom rule that bypasses the normal ODK mirroring rule to include an additional step, the addition of OBO shorthands to RO relations.
"OBO shorthands" are basically a trick allowing to use, e.g. `part_of` instead of `BFO:0000050` in a class expression, as in:
```
relationship: part_of UBERON:00000033
```
However there is no reason to forcefully inject OBO shorthands to all RO relations as we are currently doing. We can already create OBO shorthands as needed within uberon-edit, for the relationships that are actually used. For example, we already have this in uberon-edit:
```
[Typedef]
id: part_of
name: part of
xref: BFO:0000050
```
which creates the `part_of` shorthand for BFO:0000050.
We should stick to doing that for the relations we are …
=> Do not "add OBO shorthands" to the RO mirror.

.gitignore, src/ontology/Makefile, src/ontology/contexts/context-drosophila.owl, src/ontology/contexts/context-gnathostome.owl, src/ontology/contexts/context-human.owl, src/ontology/contexts/context-mouse.owl, src/ontology/contexts/context-nematode.owl, src/ontology/contexts/context-xenopus.owl, src/ontology/contexts/context-zebrafish.owl, src/ontology/uberon-odk.yaml, src/ontology/uberon.Makefile
This PR updates the way we are building “taxon subsets”.
As explained in #3362, we currently have, for reasons unknown (to me at least), two slightly different methods to create taxon subsets: one producing the `-view` subsets (`human-view`, `mouse-view`, `xenopus-view`) and one producing the `-basic` subsets (`amniote-basic`, `euarchotonglires-basic`). Both methods rely on the use of OWLTools.
This PR replaces both methods by a single one (so that all taxon subsets are produced in the same way) that relies on a new command in Uberon’s custom ROBOT plugin.
The PR does not change _which_ taxon subsets are produced and released by default (the five subsets aforementioned: `human`, `mouse`, `xenopus`, `amniote`, and `euarchotonglires`). 
More subsets can be produced on demand, all that is …
=> Overhaul taxon subsets

src/ontology/Makefile, src/ontology/uberon-odk.yaml
This PR amends the ODK import configuration to make sure that, when compiling the merged import module, IRIs from `http://www.ncbi.nlm.nih.gov/gene/` and `http://birdgenenames.org/` are filtered out. Otherwise those IRIs end up as dangling classes under `owl:Thing`.
closes #3234
=> Filter out dangling gene IRIs in imports

.github/workflows/diff.yml, .github/workflows/qc.yml, src/ontology/catalog-v001.xml, src/ontology/uberon.Makefile
This PR amends the rules that refresh the externally maintained SSSOM mapping sets (the FBbt set and the Biomappings set) to include a step that check those sets against the current version of the ontology to
(1) remove any mapping to a Uberon entity that does not exist or is deprecated;
(2) add any missing label, using the labels found in the ontology.
This necessitates, as a preliminary:
(1) making sure we are using ODK 1.5.3, as previous versions do not include a recent enough version of SSSOM-Java;
(2) removing a bogus empty `xml:base` attribute in the XML catalog, that prevents `sssom-cli` from reading it.
=> Update foreign SSSOM sets from the ontology.

src/ontology/diffs/Makefile
Fixes #3411 
While I was addressing the ticket I was conflicted if structures related to uterine tubes should have a different term for humans, since many synonyms make reference to fallopian tube. My decision was to keep them as exact synonyms (after all, uterine tube is an exact synonym of fallopian tube). 
Therefore, I believe [serosa of fallopian tube](http://purl.obolibrary.org/obo/UBERON_0012499) should be merged into [mesosalpinx](http://purl.obolibrary.org/obo/UBERON_0012331).
=> Fixes #3411 to revise 'mesosalpinx' textual/logical definition, synonyms and oviduct synonyms

.github/workflows/reviewers.yml
The main use case for this action is to provide a way to assign specific reviewers when equivalent class axioms are added or updated, but it should be easy to extend the action to other kinds of edits, hence the generic name.
To achieve the above, we check the diff for changes to rows that signify a logical definition, i.e. starting with "intersection_of". If we find such a change, we set a special environment variable to "true"; if it is "true", in the next step, a reviewer is assigned. Lastly, we let the GitHub action itself make a review, which requests changes - the idea is that these need to be dismissed by a person which sufficient access to Uberon before the change is committed to the main (master) branch.
Issue: https://github.com/obophenotype/uberon/issues/2020
=> Add GitHub action that assigns reviewers when equivalent class axioms are updated

src/ontology/uberon.Makefile
We change the `refresh-external-resources` target so that it still refreshes (1) the imports, (2) the "local" imports (in fact the local copies of the foreign ontologies used to build Composite Metazoan), (3) the externally maintained mapping sets, (4) the externally maintained bridges; **but** it does not re-generate the bridge files that are dependent on the refreshed mappings.
The mappings-derived bridges are now expected to be built at release time (and also at QC time). We build them under `MIR=false`, so they will only be built using the locally available mappings (from the last time they were refreshed), without triggering the download of any remote resource.
Editors/maintainers can still locally trigger the building of the bridge files at any time by explicitly invoking the …
=> Uncouple bridge generation from mappings refresh.

docs/uberon-editor-sop.md
The Uberon editor SOP is still recommending that synonyms that are abbreviations should be marked with the synonym type `http://purl.obolibrary.org/obo/uberon/core#ABBREVIATION`.
We have phased out the use of this particular synonym type several months (maybe years?) ago, in favour of the OMO-defined synonym type `OMO:0003000`. So here we simply amend the SOP to recommend using the OMO-defined type.
=> Amend Uberon editor SOP about "abbreviation" synonyms.

src/scripts/mappings-to-xrefs.rules
Most of the prefixes used by the taxon-specific life stage ontologies (SSLSO) are not intrinsically known by ROBOT (prefixes such as BtauDv, GgalDv, PpanDv, etc.).
As a result, when the mappings from SSLSO are transformed into cross-references for injection into the ontology (when we create the `mappings.owl` component), the SSLSO term IDs are shortened using the only suitable prefix that ROBOT knows about, the `obo:` prefix.
This means that a mapping to, say, <http://purl.obolibrary.org/obo/BtauDv_0000078> gets turned into a cross-reference to `obo:BtauDv_0000078` -- which is, strictly speaking, correct, but _not_ the format most people would expect for OBO-style cross-references (which would be `BtauDv:0000078`).
The fix is simply to make sure the prefixes are correctly declared.
=> Make sure the SSSOM-derived cross-reference use correct OBO prefixes.

src/ontology/config/taxa.yaml
Now that SSLSO includes the ChirDv (goat life stages) component, we must make sure the bridging/composite pipeline is ready to deal with that component: that is, we must generate bridging axioms between the Uberon life stages terms and their ChirDv counterparts, and unfold them into class expressions when building Composite Metazoan.
Otherwise, the ChirDv terms would still end up in the collected/composite products (since they are bundled with SSLSO), but would not be connected to Uberon’s hierarchy.
=> Integrate ChirDv into the composite pipeline.

.github/workflows/diff.yml, .github/workflows/qc.yml
This PR updates the GitHub Actions workflow files to make them use the latest 1.5.4 version of the ODK.
The bridge generation pipeline now requires SSSOM-Java 1.0.0 (this has been the case since #3443), which in turns requires the ODK 1.5.4.
=> Use ODK 1.5.4 in GitHub Actions workflows.

src/scripts/mappings-to-xrefs.rules
When generating the cross-references from the SSSOM-maintained mappings, annotate them with any seeAlso annotations that may be associated with the mappings.
The intention is that, if a mapping editor has a reference to back up a mapping statement, that reference can be stored in the SSSOM `see_also` field, and once there it should be preserved when the mapping is transformed into a classic cross-reference.
(This is the same thing as the [corresponding CL PR](https://github.com/obophenotype/cell-ontology/pull/3022)).
=> Include seeAlso annotations in mapping-derived xrefs.

.github/workflows/diff.yml
The `diff.yml` workflow, which powers the “gogoeditdiff” feature, is still using the ODK image version 1.5.4. This leads to a systematic failure, because at least one of the rules invoked by this workflow (`make uberon-base.owl`) is dependent upon the new ROBOT option `--include-subproperties`, which is not available in the version of ROBOT provided with ODK 1.5.4.
We update the workflow to ensure it uses version 1.6 of the ODK.
closes #3575
=> Use ODK 1.6 in diff.yml workflow.

.github/workflows/allocate-definitive-ids.yml, docs/id-management.md, mkdocs.yaml, src/ontology/uberon-idranges.owl, src/ontology/uberon.Makefile
This PR implements the idea proposed in #3564 for allowing AI agents (or in fact any editor, AI or not) to use “temporary” term IDs that are later replaced by definitive IDs.
It allocates two new ID ranges:
* the `Temporary IDs` range (UBERON:99NNNNN): any ID picked within that range is treated as a temporary ID, slated for later replacement by a definitive ID;
* the `Automation` range (UBERON:12NNNNN): this is a “normal” ID range (IDs picked within that range are not treated differently from any other ID), but is reserved for automated process – notably, for the process that replaces temporary IDs by definitive ones.
It also adds a new GitHub Action workflow, `allocate-definitive-ids.yml`, which finds all temporary IDs (all IDs in the `UBERON:99NNNNN` range) in the -edit file and …
=> Support temporary IDs

.github/workflows/allocate-definitive-ids.yml
The automatic ID allocation workflow currently cannot be used in fully automated mode (after a PR has been merged), because it will always use the default `GITHUB_TOKEN`, which is not allowed to push to the master branch.
The workflow has a dedicated token (which _is_ allowed to push to the master branch) specifically intended for the purpose of automatic ID allocation, but for the push step to use it, the checkout step needs to be configured _not_ to persist the checkout credentials, which is what we do here.
=> Fix the automatic ID allocation workflow.
